# Generated by Django 5.1.1 on 2024-11-07 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagamodel',
            name='descritivo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descritivo da Vaga'),
        ),
        migrations.AddField(
            model_name='vagamodel',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail da Empresa'),
        ),
    ]
